// dropbox-like.idl
// IDL definition of a distributed file repository

module dropboxlike
{
    //Bind a specific user to the device is using
    struct Device{
        string username;
        string dev_id;
    };
    struct Logged {
        Device dev;
        string token;
    };

    //It contains the information about a specific user
    struct UserInfo { 
        string name;
        string surname;
        string username;
        string password;
    };
    
    exception AlreadySubscribed { };
    exception InvalidUser{ };
    exception UserNoLogged { };
    
    //It describes the login/logout/subscribe module
    interface UserManager {
        boolean isLogged(in string username);
        boolean subscribe(in string name, in string surname, in string username, in string password) raises (AlreadySubscribed);
        boolean login(in string username, in string password, in string dev_id) raises (InvalidUser);
        boolean logout (in string username, in string device) raises (UserNoLogged);
        readonly attribute Logged logged;
    };
    
    //I 
    struct FileAtRepository { 
        string  name;
        string  md5;
        string  ownerUserName;
    };
    
    exception ErrorFileSending { };
    
    interface Repository {
        boolean send(in FileAtRepository file) raises (ErrorFileSending);
        boolean ask_list_user (in string file_md5);
    };
};
